Repository ansible/django-ansible-base, pull requests merged in 2024-05, with the labels that each got.

#357 Add RBAC and documentation links to v1 page
  test_app/views.py
Labels: api, app:test_app

#362 Using cache in jwt authentication
  ansible_base/jwt_consumer/common/auth.py
  test_app/tests/conftest.py
  test_app/tests/jwt_consumer/common/test_auth.py
Labels: Ready for review

#331 [translations] /rest_filters updates
  ansible_base/rest_filters/rest_framework/field_lookup_backend.py
  ansible_base/rest_filters/utils.py
Labels: Ready To Merge

#364 Fix bug detecting running container that needs migration
  test_app/scripts/bootstrap.sh
Labels: app:test_app, Ready for review

#382 Remove logo_data from OAuth2Application
  ansible_base/oauth2_provider/migrations/0003_remove_oauth2application_logo_data.py
  ansible_base/oauth2_provider/models/application.py
Labels: Ready for review

#375 Disallow editing of system user
  ansible_base/lib/serializers/common.py
  test_app/serializers.py
  test_app/tests/lib/serializers/test_common.py
Labels: Ready for review

#311 Add resource server config
  ansible_base/resource_registry/models/resource.py
  ansible_base/resource_registry/resource_server.py
  ansible_base/resource_registry/rest_client.py
  ansible_base/resource_registry/views.py
  test_app/authentication/service_token_auth.py
  test_app/settings.py
  test_app/tests/resource_registry/test_resources_api_rest_client.py
Labels: comments left

#394 Add check for system user does not exist
  ansible_base/lib/serializers/common.py
  test_app/tests/lib/serializers/test_common.py
Labels: Ready for review

#370 Fix 500 on unintended endpoints and further refactor association router
  ansible_base/lib/routers/association_resource_router.py
  docs/lib/routers.md
  test_app/router.py
  test_app/tests/conftest.py
  test_app/tests/lib/routers/test_association_resoure_router.py
  test_app/tests/rbac/conftest.py
  test_app/views.py
Labels: Ready for review

#381 Add file and unix URL support to the redis client
  ansible_base/lib/redis/client.py
  test_app/tests/lib/redis/test_client.py
Labels: Ready for review

#401 Fix `IntegrityError` when giving overlapping team permissions
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/rbac/caching.py
Labels: Ready for review

#377 More fixes from warnings in /docs/ page
  ansible_base/activitystream/serializers.py
  ansible_base/api_documentation/apps.py
  ansible_base/api_documentation/customizations.py
  test_app/authentication/logged_basic_auth.py
  test_app/tests/activitystream/test_api.py
Labels: Ready for review

#413 RBAC: User can't delete self
  ansible_base/rbac/api/permissions.py
  ansible_base/rbac/policies.py
  test_app/tests/rbac/api/test_user_permissions.py
Labels: Ready To Merge

#399 Fetch is_superuser/is_system_auditor/groups for OIDC, Keycloak, SAML
  ansible_base/authentication/authenticator_plugins/keycloak.py
  ansible_base/authentication/authenticator_plugins/oidc.py
  ansible_base/authentication/authenticator_plugins/saml.py
  ansible_base/authentication/social_auth.py
  test_app/tests/authentication/authenticator_plugins/test_keycloak.py
  test_app/tests/authentication/authenticator_plugins/test_oidc.py
  test_app/tests/authentication/authenticator_plugins/test_saml.py
Labels: Ready for review

#411 disable POST in options for role definitions if custom roles disabled
  ansible_base/rbac/api/permissions.py
  ansible_base/rbac/api/views.py
  test_app/tests/rbac/api/test_rbac_views.py
Labels: Ready To Merge

#297 Implement periodic sync command and functions.
  ansible_base/lib/testing/util.py
  ansible_base/resource_registry/management/__init__.py
  ansible_base/resource_registry/management/commands/__init__.py
  ansible_base/resource_registry/management/commands/resource_sync.py
  ansible_base/resource_registry/rest_client.py
  ansible_base/resource_registry/tasks/__init__.py
  ansible_base/resource_registry/tasks/sync.py
  docs/apps/resource_registry.md
  test_app/tests/fixtures/static/resource_sync/metadata/response
  test_app/tests/fixtures/static/resource_sync/resource-types/shared.organization/manifest/response
  test_app/tests/fixtures/static/resource_sync/resource-types/shared.user/manifest/response
  test_app/tests/fixtures/static/resource_sync/resources/31daab14-cb67-4c62-8dcd-39f411c82242/response
  test_app/tests/fixtures/static/resource_sync/resources/3e3cc6a4-72fa-43ec-9e17-76ae5a3846ca/response
  test_app/tests/fixtures/static/resource_sync/resources/97447387-8596-404f-b0d0-6429b04c8d22/response
  test_app/tests/resource_registry/test_resource_sync.py
Labels: question, Ready for review

#414 disallow filtering by encrypted_fields
  ansible_base/rest_filters/utils.py
  test_app/tests/rest_filters/test_utils.py
Labels: Ready To Merge
