Repository ansible/django-ansible-base, pull requests merged in 2024-06, with the labels that each got.

#419 Use dynamic docstrings for sublists
  ansible_base/lib/routers/association_resource_router.py
  test_app/tests/lib/routers/test_association_resoure_router.py
Labels: Ready for review

#436 Fix SSO/radius bug
  ansible_base/authentication/authenticator_plugins/radius.py
Labels: Ready To Merge

#434 Lock down OAuth2 views
  ansible_base/lib/utils/views/permissions.py
  ansible_base/oauth2_provider/migrations/0004_alter_oauth2accesstoken_scope.py
  ansible_base/oauth2_provider/models/access_token.py
  ansible_base/oauth2_provider/serializers/token.py
  ansible_base/oauth2_provider/views/application.py
  ansible_base/oauth2_provider/views/permissions.py
  ansible_base/oauth2_provider/views/token.py
  test_app/tests/activitystream/test_api.py
  test_app/tests/oauth2_provider/test_rbac.py
  test_app/tests/oauth2_provider/views/test_application.py
  test_app/tests/oauth2_provider/views/test_token.py
Labels: comments left

#389 Replace X-TRUSTED-HEADER with pub/priv encrypted message
  ansible_base/jwt_consumer/common/auth.py
  ansible_base/jwt_consumer/common/cache.py
  ansible_base/jwt_consumer/common/cert.py
  ansible_base/jwt_consumer/common/util.py
  ansible_base/lib/testing/fixtures.py
  ansible_base/lib/utils/encryption.py
  ansible_base/lib/utils/requests.py
  docs/lib/requests.md
  test_app/settings.py
  test_app/tests/fixtures/test_fixtures.py
  test_app/tests/jwt_consumer/common/test_auth.py
  test_app/tests/jwt_consumer/common/test_cache.py
  test_app/tests/jwt_consumer/common/test_cert.py
  test_app/tests/jwt_consumer/common/test_util.py
  test_app/tests/lib/utils/test_encryption.py
  test_app/tests/lib/utils/test_requests.py
Labels: Ready for review

#430 Prevent role assignment or removal of unmanaged things
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/rbac/api/serializers.py
  ansible_base/rbac/api/views.py
  ansible_base/rbac/validators.py
  test_app/tests/rbac/api/test_rbac_validation.py
Labels: Ready To Merge

#421 oauth2_provider: support adding, removing, clearing tokens
  ansible_base/oauth2_provider/management/commands/cleanup_tokens.py
  ansible_base/oauth2_provider/management/commands/create_oauth2_token.py
  ansible_base/oauth2_provider/management/commands/revoke_oauth2_tokens.py
  test_app/tests/oauth2_provider/management/commands/test_cleanup_tokens.py
  test_app/tests/oauth2_provider/management/commands/test_create_oauth2_token.py
  test_app/tests/oauth2_provider/management/commands/test_revoke_oauth2_tokens.py
Labels: Ready To Merge

#441 fix: Do not convert jwt_user_id from None to str
  ansible_base/resource_registry/rest_client.py
Labels: Ready for review

#431 Reconcile User Claims with AuthMap roles
  ansible_base/authentication/utils/claims.py
  ansible_base/lib/testing/fixtures.py
  test_app/tests/authentication/conftest.py
  test_app/tests/authentication/utils/test_claims.py
  test_app/tests/authentication/utils/test_claims_orgs_and_teams.py
  test_app/tests/authentication/utils/test_claims_reconcile_user.py
Labels: Ready for review

#442 fix: make RESOURCE_JWT_USER_ID and RESOURCE_SERVICE_PATH optional.
  ansible_base/resource_registry/tasks/sync.py
  docs/apps/resource_registry.md
  test_app/tests/resource_registry/test_resource_sync.py
Labels: Ready for review

#461 Prevent system user from logging in via external source
  ansible_base/authentication/utils/authentication.py
Labels: Ready To Merge

#462 Fix typo in keycloak public key help text
  docs/apps/authentication/authenticator_plugins.md
Labels: Ready To Merge

#471 Respect admin password env var and remove duplication creation
  test_app/management/commands/create_demo_data.py
  test_app/scripts/bootstrap.sh
  test_app/tests/test_demo_data.py
Labels: Ready To Merge

#427 Split DAB RBAC app docs into 4 parts by intended audience
  ansible_base/rbac/api/views.py
  docs/apps/rbac/README.md
  docs/apps/rbac/for_app_developers.md
  docs/apps/rbac/for_clients.md
  docs/apps/rbac/for_dab_developers.md
  docs/apps/rbac/for_users.md
  docs/apps/rbac/images/team_obj.svg
  docs/apps/rbac/images/team_org.svg
  docs/apps/rbac/images/user_obj.svg
  docs/apps/rbac/images/user_org.svg
  docs/apps/rbac/images/user_system.svg
Labels: Ready To Merge, comments left

#460 Remove OIDC backend config data caching
  ansible_base/authentication/authenticator_plugins/oidc.py
Labels: Ready for review

#464 Add another variable which might house the public cert
  ansible_base/jwt_consumer/common/cert.py
Labels: question

#448 Add handling for jwt enc OIDC user info
  ansible_base/authentication/authenticator_plugins/oidc.py
  test_app/tests/authentication/authenticator_plugins/test_oidc.py
Labels: comments left

#479 Add a test for permission transference moving teams org
  test_app/tests/rbac/test_permission_assignment.py
Labels: Ready To Merge

#452 More robust proxy trust header handling
  ansible_base/jwt_consumer/common/util.py
Labels: comments left

#463 Social Auth reflects Authentication maps
  ansible_base/authentication/backend.py
  ansible_base/authentication/social_auth.py
  test_app/tests/authentication/test_backend.py
Labels: Ready for review

#473 Add test model with no view permission
  ansible_base/rbac/evaluations.py
  ansible_base/rbac/validators.py
  docs/apps/rbac/for_app_developers.md
  test_app/migrations/0011_publicdata.py
  test_app/models.py
  test_app/router.py
  test_app/serializers.py
  test_app/tests/lib/abstract_models/test_common.py
  test_app/tests/rbac/features/test_public_model.py
  test_app/views.py
Labels: Ready To Merge

#437 Fix issues with saving secrets starting with $encrypted$
  ansible_base/authentication/models/authenticator.py
  ansible_base/lib/abstract_models/common.py
  ansible_base/lib/utils/encryption.py
  ansible_base/rbac/api/permissions.py
  ansible_base/rbac/api/serializers.py
  docs/lib/encryption.md
  test_app/tests/jwt_consumer/common/test_util.py
  test_app/tests/lib/utils/test_encryption.py
Labels: comments left

#481 Disable activitystream for access token last_used
  ansible_base/oauth2_provider/models/access_token.py
  test_app/tests/oauth2_provider/test_authentication.py
Labels: Ready To Merge

#487 Fix authenticator-related users view with permission handling
  ansible_base/authentication/views/authenticator_users.py
  test_app/tests/authentication/views/test_authenticator_user.py
Labels: Ready for review

#467 Add social auth exception handler middleware
  ansible_base/authentication/middleware.py
  ansible_base/lib/dynamic_config/dynamic_settings.py
  test_app/tests/authentication/test_middleware.py
  test_app/tests/lib/dynamic_config/test_dynamic_settings.py
Labels: Ready To Merge

#494 Fix typo in github field label name for scope.
  ansible_base/authentication/authenticator_configurators/github.py
Labels: Ready To Merge

#425 Fix queryset of RoleDefinition-assignment list with new utils
  ansible_base/rbac/api/views.py
  ansible_base/rbac/models.py
  test_app/tests/rbac/api/test_rbac_views.py
Labels: bug, app:rbac, Ready To Merge

#478 Enhancements to request logging
  ansible_base/lib/logging/__init__.py
  ansible_base/lib/logging/filters/__init__.py
  ansible_base/lib/logging/filters/request_id.py
  ansible_base/lib/middleware/__init__.py
  ansible_base/lib/middleware/logging/__init__.py
  ansible_base/lib/middleware/logging/log_request.py
  ansible_base/lib/utils/collection.py
  docs/logging.md
  test_app/settings.py
  test_app/tests/lib/logging/filters/test_request_id.py
  test_app/views.py
Labels: Ready To Merge
