Repository ansible/django-ansible-base, pull requests merged in 2024-08, with the labels that each got.

#542 Add bits necessary to satiate pulpcore's openapi generator.
  ansible_base/lib/utils/views/ansible_base.py
Labels: galaxy

#541 Fix authenticator order
  ansible_base/authentication/migrations/0013_alter_authenticator_order.py
  ansible_base/authentication/models/authenticator.py
  test_app/tests/authentication/models/test_authenticator.py
Labels: Ready for review

#531 Nest the dynamic settings inclusion into a method
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/lib/dynamic_config/settings_logic.py
  docs/Installation.md
  docs/apps/rest_filters.md
Labels: galaxy

#532 Fix validation bug creating invalid custom system roles
  ansible_base/rbac/validators.py
  test_app/tests/rbac/api/test_rbac_serializers.py
Labels: galaxy

#538 Fix bug with reference to id as opposed to pk
  ansible_base/rbac/triggers.py
  test_app/tests/rbac/compatibility/test_non_id_primary_key.py
Labels: galaxy

#551 Test concrete inheritance and fix error with nested inheritance
  ansible_base/rbac/models.py
  ansible_base/rbac/triggers.py
  test_app/migrations/0014_autoextrauuidmodel_manualextrauuidmodel_and_more.py
  test_app/models.py
  test_app/tests/rbac/compatibility/conftest.py
  test_app/tests/rbac/compatibility/test_concrete_inheritance.py
  test_app/tests/rbac/compatibility/test_uuid_support.py
Labels: galaxy

#535 Altering redis client - breaking change
  ansible_base/lib/redis/client.py
  docs/lib/redis.md
  test_app/tests/lib/redis/test_client.py
Labels: comments left

#447 resource_registry: sync organization and team descriptions across services
  ansible_base/resource_registry/shared_types.py
  test_app/tests/fixtures/static/resource_sync/resources/3e3cc6a4-72fa-43ec-9e17-76ae5a3846ca/response
Labels: Ready To Merge

#560 Fix bug where is_registered did not consider app_label
  ansible_base/rbac/permission_registry.py
  test_app/migrations/0015_logentry.py
  test_app/models.py
  test_app/tests/rbac/compatibility/test_model_name_conflict.py
Labels: galaxy

#545 Add method to get status from redis
  ansible_base/lib/constants.py
  ansible_base/lib/redis/client.py
  test_app/tests/lib/redis/test_client.py
Labels: Ready for review

#570 fix: coerce reading saml request as via https if REDIRECT_IS_HTTPS
  ansible_base/authentication/authenticator_plugins/saml.py
  test_app/tests/authentication/authenticator_plugins/test_saml.py
Labels: Ready for review

#573 RBAC content filter should consider the app_label.
  ansible_base/rbac/api/serializers.py
  ansible_base/rbac/permission_registry.py
  test_app/tests/rbac/compatibility/test_model_name_conflict.py
Labels: app:rbac

#563 Give 400 respones when roles violate RBAC validators
  ansible_base/rbac/api/serializers.py
  ansible_base/rbac/evaluations.py
  test_app/tests/rbac/api/test_rbac_validation.py
Labels: app:rbac, Ready To Merge

#576 Delete resources so reverse migrations will work
  ansible_base/resource_registry/migrations/0002_remove_resource_id.py
Labels: app:resource_registry, Ready To Merge

#577 Add tests for more than 1 team and org member roles
  test_app/tests/rbac/test_permission_evaluation.py
Labels: app:rbac, Ready for review

#565 Add service backed SSO
  ansible_base/resource_registry/utils/auth_code.py
  ansible_base/resource_registry/utils/service_backed_sso_pipeline.py
  ansible_base/resource_registry/utils/sso_provider.py
  docs/apps/service_backed_sso.md
  test_app/settings.py
  test_app/tests/resource_registry/test_service_backed_sso.py
Labels: app:resource_registry

#562 Use updated heuristic for identifying locally managed roles
  ansible_base/lib/dynamic_config/settings_logic.py
  ansible_base/rbac/api/serializers.py
  ansible_base/rbac/api/views.py
  ansible_base/rbac/validators.py
  test_app/settings.py
  test_app/tests/rbac/api/test_rbac_validation.py
  test_app/tests/rbac/api/test_rbac_views.py
  test_app/tests/rbac/api/test_user_permissions.py
Labels: app:resource_registry, app:rbac, galaxy

#586 Add oidc_alt_key to auth code
  ansible_base/resource_registry/utils/auth_code.py
  ansible_base/resource_registry/utils/service_backed_sso_pipeline.py
  test_app/tests/resource_registry/test_service_backed_sso.py
Labels: app:resource_registry

#572 Add fallback cache
  ansible_base/lib/cache/fallback_cache.py
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/lib/dynamic_config/settings_logic.py
  ansible_base/lib/redis/client.py
  test_app/tests/lib/cache/__init__.py
  test_app/tests/lib/cache/test_cache.py
  test_app/tests/lib/utils/test_settings.py
Labels: app:lib, Ready for review

#584 Ignore permissions given twice in migrations
  ansible_base/rbac/migrations/_utils.py
  test_app/tests/rbac/test_migrations.py
Labels: app:rbac, Ready To Merge

#581 [AAP-27692] Add middleware that apps can use to handle graceful timeout signal
  ansible_base/lib/middleware/logging/__init__.py
  ansible_base/lib/middleware/logging/log_request.py
  docs/logging.md
  test_app/settings.py
  test_app/tests/lib/logging/middleware/test_traceback_logger.py
  test_app/urls.py
  test_app/uwsgi.ini
  test_app/views.py
Labels: app:lib
