Repository ansible/django-ansible-base, pull requests merged in 2024-07, with the labels that each got.

#502 Handle system user login via external source
  ansible_base/authentication/utils/authentication.py
  ansible_base/lib/channels/middleware.py
  test_app/tests/authentication/utils/test_authentication.py
Labels: Ready To Merge

#480 Fix AuthMap groups and attributes rules
  ansible_base/authentication/utils/claims.py
  test_app/tests/authentication/utils/test_claims.py
Labels: Ready for review

#486 jwt_consumer: remove unauthorized permissions
  ansible_base/jwt_consumer/common/auth.py
  ansible_base/lib/dynamic_config/dynamic_settings.py
  test_app/settings.py
  test_app/tests/jwt_consumer/common/test_auth.py
Labels: Ready To Merge

#497 Require superuser permission to revoke global roles
  ansible_base/rbac/api/serializers.py
  ansible_base/rbac/api/views.py
  ansible_base/rbac/policies.py
  ansible_base/rbac/validators.py
  test_app/tests/conftest.py
  test_app/tests/jwt_consumer/common/test_auth.py
  test_app/tests/rbac/api/test_assignment_permissions.py
  test_app/tests/rbac/api/test_rbac_validation.py
  test_app/tests/rbac/api/test_rbac_views.py
Labels: Ready for review

#518 Fix incorrect mock object calls
  test_app/tests/authentication/authenticator_plugins/test_oidc.py
  test_app/tests/authentication/authenticator_plugins/test_radius.py
Labels: Ready To Merge

#515 Use single postgres definition in compose file
  Makefile
  docker-compose.yml
Labels: Ready To Merge

#512 Make ansible_id match the JWT data if creating new user
  ansible_base/jwt_consumer/common/auth.py
  test_app/tests/jwt_consumer/common/test_auth.py
Labels: Ready To Merge

#517 [Low Prio] Add a sqlite3 check
  .github/workflows/ci.yml
  pyproject.toml
  test_app/tests/authentication/views/test_authenticator_map.py
Labels: comments left

#519 Adding setting to prevent modification of settings in AoC environment
  ansible_base/authentication/views/ui_auth.py
  ansible_base/lib/utils/settings.py
  test_app/tests/authentication/views/test_ui_auth.py
  test_app/tests/lib/utils/test_settings.py
Labels: Ready for review

#508 [Low Prio] Add uwsgi + nginx + ssl to the compose stack
  .gitignore
  compose/ingress/Dockerfile
  compose/ingress/certs/.keepme
  compose/ingress/entrypoint.sh
  compose/ingress/nginx.conf
  compose/nginx/nginx.conf
  docker-compose.yml
  test_app/scripts/container_startup_uwsgi.sh
  test_app/uwsgi.ini
  test_app/wsgi.py
Labels: comments left

#520 Error if Delete permission is issued without Change permission
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/rbac/validators.py
  test_app/tests/rbac/features/test_public_model.py
  test_app/tests/rbac/test_validators.py
Labels: comments left

#521 fix: Skip _system user when syncing resources
  ansible_base/resource_registry/views.py
  test_app/tests/fixtures/static/resource_sync/resource-types/shared.user/manifest/response
  test_app/tests/fixtures/static/resource_sync/resources/31daab14-cb67-4c62-8dcd-39f411c82242/response
  test_app/tests/resource_registry/test_resource_sync.py
Labels: Ready To Merge

#522 Prepare 2 User managers to exclude _system user by default
  ansible_base/lib/abstract_models/__init__.py
  ansible_base/lib/abstract_models/user.py
  ansible_base/lib/utils/create_system_user.py
  ansible_base/lib/utils/models.py
  test_app/managers.py
  test_app/migrations/0013_alter_manageduser_managers_alter_user_managers.py
  test_app/models.py
  test_app/tests/lib/utils/test_create_system_user.py
Labels: Ready for review
