Repository ansible/django-ansible-base, pull requests merged in 2024-04, with the labels that each got.

#262 Be able to shut up activity stream
  ansible_base/activitystream/__init__.py
  ansible_base/activitystream/signals.py
  test_app/tests/activitystream/test_signals.py
Labels: Ready To Merge

#261 [activitystream] Make DRF render more nicely
  ansible_base/activitystream/urls.py
  ansible_base/activitystream/views.py
  test_app/tests/activitystream/test_api.py
Labels: Ready To Merge, comments left

#270 Squash RBAC migrations while we can
  ansible_base/rbac/migrations/0001_initial.py
  ansible_base/rbac/migrations/0002_alter_roledefinition_created_by_and_more.py
Labels: Ready for review

#272 Sonar doesn't like passwords in tests
  test_app/tests/lib/redis/test_client.py
Labels: Ready To Merge

#276 Add typing necessary to satisfy eda-server OpenAPI issues
  ansible_base/activitystream/serializers.py
  ansible_base/lib/routers/association_resource_router.py
  ansible_base/rbac/api/serializers.py
  ansible_base/resource_registry/serializers.py
Labels: Ready for review

#254 [translations] common/auth update
  ansible_base/jwt_consumer/common/auth.py
  ansible_base/lib/utils/translations.py
  test_app/tests/jwt_consumer/common/test_auth.py
Labels: Ready To Merge

#288 Include activity stream link in root test_app view
  test_app/views.py
Labels: Ready for review

#289 Fix failing AWX checks due to schema issues
  ansible_base/resource_registry/views.py
Labels: Ready for review

#281 Transaction-safe ObjectRole creation
  ansible_base/rbac/models.py
  test_app/tests/rbac/models/test_object_role.py
Labels: Ready for review

#298 Allow for customizing the automatic creator role
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/rbac/models.py
Labels: Ready for review

#284 Use correct common parent for service-index
  ansible_base/resource_registry/views.py
Labels: Ready for review

#260 Fix enablement problem with typeguard
  ansible_base/authentication/authenticator_plugins/utils.py
  ansible_base/authentication/urls.py
  ansible_base/lib/utils/encryption.py
  ansible_base/rbac/models.py
  ansible_base/rbac/permission_registry.py
  ansible_base/rbac/triggers.py
  ansible_base/rbac/validators.py
  ansible_base/resource_registry/models/resource.py
  ansible_base/resource_registry/registry.py
  pyproject.toml
  test_app/resource_api.py
  test_app/settings.py
Labels: Ready for review

#301 Add User to unique constraint on AuthenticatorUser
  ansible_base/authentication/migrations/0006_alter_authenticatoruser_unique_together.py
  ansible_base/authentication/models/social_auth.py
Labels: Ready for review

#292 Exclude last_login from test_app's User model activity stream entries
  test_app/models.py
Labels: Ready for review

#282 [activity stream] Store string-coerced values
  ansible_base/activitystream/filtering.py
  ansible_base/activitystream/serializers.py
  ansible_base/activitystream/signals.py
  ansible_base/activitystream/views.py
  ansible_base/lib/utils/models.py
  ansible_base/rest_filters/rest_framework/field_lookup_backend.py
  ansible_base/rest_filters/utils.py
  docs/apps/activitystream.md
  docs/apps/rest_filters.md
  test_app/migrations/0005_city.py
  test_app/models.py
  test_app/router.py
  test_app/serializers.py
  test_app/tests/activitystream/test_api.py
  test_app/tests/activitystream/test_signals.py
  test_app/tests/rest_filters/rest_framework/test_field_lookup_backend.py
  test_app/views.py
Labels: app:activity_stream, Ready for review

#293 Fix validation error for role definition PATCH
  ansible_base/rbac/api/serializers.py
  test_app/tests/rbac/api/test_rbac_serializers.py
Labels: bug, Ready To Merge

#264 Remove object_role from RBAC API, cleanup logging
  ansible_base/rbac/api/permissions.py
  ansible_base/rbac/api/serializers.py
  ansible_base/rbac/migrations/0001_initial.py
  ansible_base/rbac/models.py
  test_app/migrations/0001_initial.py
  test_app/migrations/0004_multiplefieldsmodel_animal.py
  test_app/migrations/0005_city.py
  test_app/models.py
  test_app/router.py
  test_app/serializers.py
  test_app/views.py
Labels: comments left, Ready for review

#240 Add internationalization to authenticator plugins
  ansible_base/authentication/authenticator_plugins/base.py
  ansible_base/authentication/authenticator_plugins/ldap.py
  ansible_base/authentication/authenticator_plugins/local.py
  ansible_base/authentication/authenticator_plugins/saml.py
Labels: comments left

#294 Remove User FK from Authenticator in favor of AuthenticatorUser
  ansible_base/authentication/backend.py
  ansible_base/authentication/migrations/0007_remove_authenticator_users_and_more.py
  ansible_base/authentication/models/authenticator.py
  ansible_base/authentication/models/social_auth.py
  ansible_base/authentication/urls.py
  ansible_base/authentication/views/authenticator_users.py
  test_app/settings.py
  test_app/tests/authentication/test_urls.py
  test_app/tests/authentication/views/test_authenticator_user.py
  test_app/tests/conftest.py
Labels: Ready for review

#302 Remove users_unique from Authenticators
  ansible_base/authentication/migrations/0008_remove_authenticator_users_unique.py
  ansible_base/authentication/models/authenticator.py
  ansible_base/lib/testing/fixtures.py
  test_app/tests/authentication/authenticator_plugins/test_ldap.py
  test_app/tests/authentication/authenticator_plugins/test_local.py
  test_app/tests/authentication/authenticator_plugins/test_oidc.py
  test_app/tests/authentication/authenticator_plugins/test_saml.py
  test_app/tests/authentication/authenticator_plugins/test_tacacs.py
  test_app/tests/authentication/serializers/test_authenticator.py
  test_app/tests/conftest.py
  test_app/tests/lib/serializers/test_validate.py
Labels: Ready for review

#291 Remove duplication from test_app team users relationship
  docs/apps/rbac.md
  test_app/migrations/0001_initial.py
  test_app/models.py
  test_app/tests/conftest.py
  test_app/tests/rbac/conftest.py
  test_app/tests/rbac/features/test_role_tracking.py
  test_app/tests/resource_registry/test_resources_api_rest_client.py
Labels: Ready To Merge

#305 Add util which can tell if a user can change their password
  ansible_base/authentication/utils/user.py
  ansible_base/lib/utils/models.py
  test_app/tests/authentication/utils/test_user.py
  test_app/tests/lib/utils/test_models.py
Labels: comments left, Ready for review

#249 Revert "Cut an automatic create-only serializer for eda-server consistency"
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/lib/utils/views/ansible_base.py
  docs/lib/views.md
  test_app/settings.py
  test_app/tests/lib/serializers/test_common.py
Labels: Ready To Merge

#312 Add 'managed_cloud_install' to ui_auth endpoint
  ansible_base/authentication/views/ui_auth.py
  test_app/tests/authentication/views/test_ui_auth.py
Labels: Ready for review

#295 [translations] update ansible_base/rbac
  ansible_base/rbac/api/serializers.py
  ansible_base/rbac/api/views.py
Labels: comments left

#319 Continuing internationalization of strings
  ansible_base/authentication/management/commands/authenticators.py
  ansible_base/authentication/models/authenticator_map.py
  ansible_base/authentication/serializers/authenticator.py
  ansible_base/authentication/views/ui_auth.py
Labels: Ready To Merge

#322 Change required logic on plugin configuration
  ansible_base/authentication/authenticator_plugins/base.py
  test_app/tests/authentication/authenticator_plugins/test_base.py
Labels: Ready for review

#316 [activitystream] Do not fatal on model deletion
  ansible_base/activitystream/serializers.py
  test_app/tests/activitystream/test_api.py
Labels: Ready To Merge

#314 [activitystream] Add back lost filter_backends
  ansible_base/activitystream/views.py
  test_app/tests/activitystream/test_api.py
Labels: Ready To Merge

#328 Fix authenticator/:id/users endpoint
  ansible_base/authentication/serializers/authenticator.py
  ansible_base/authentication/urls.py
  ansible_base/authentication/views/authenticator_users.py
  test_app/tests/authentication/views/test_authenticator_user.py
Labels: Ready for review

#90 Exclude redundant files from source distribution
  MANIFEST.in
Labels: Ready To Merge

#313 [activitystream] Make related and summary_fields a bit more useful
  ansible_base/activitystream/migrations/0003_alter_entry_options.py
  ansible_base/activitystream/models/entry.py
  ansible_base/activitystream/serializers.py
  ansible_base/activitystream/views.py
  ansible_base/lib/abstract_models/common.py
  test_app/router.py
  test_app/serializers.py
  test_app/tests/activitystream/test_api.py
  test_app/views.py
Labels: comments left

#330 Internationalization for lib & resource_registry dirs
  ansible_base/lib/abstract_models/common.py
  ansible_base/resource_registry/registry.py
Labels: Ready To Merge

#303 Avoid putting ignored fields in summary_fields
  ansible_base/lib/abstract_models/common.py
  test_app/models.py
  test_app/tests/lib/abstract_models/test_common.py
  test_app/tests/rbac/api/test_rbac_views.py
Labels: comments left

#344 Make id the default order field
  ansible_base/rest_filters/rest_framework/order_backend.py
  test_app/tests/rest_filters/rest_framework/test_order_backend.py
Labels: Ready for review

#343 Allow m2m relations in related_fields
  ansible_base/lib/abstract_models/common.py
  test_app/tests/lib/abstract_models/test_common.py
Labels: Ready for review

#337 Remove permission_classes from un-opinionated views to allow customization
  ansible_base/authentication/views/authenticator.py
  ansible_base/authentication/views/authenticator_map.py
Labels: Ready To Merge, comments left

#280 Alter authentication
  ansible_base/authentication/authenticator_plugins/ldap.py
  ansible_base/authentication/authenticator_plugins/local.py
  ansible_base/authentication/authenticator_plugins/tacacs.py
  ansible_base/authentication/models/__init__.py
  ansible_base/authentication/models/authenticator_user.py
  ansible_base/authentication/social_auth.py
  ansible_base/authentication/utils/authentication.py
  ansible_base/authentication/utils/claims.py
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/lib/testing/fixtures.py
  docs/apps/authentication/authenticator_plugins.md
  test_app/tests/authentication/authenticator_plugins/test_ldap.py
  test_app/tests/authentication/authenticator_plugins/test_local.py
  test_app/tests/authentication/authenticator_plugins/test_tacacs.py
  test_app/tests/authentication/utils/test_authentication.py
Labels: Ready for review

#346 Allow configuring permissions needed to related objects
  ansible_base/lib/dynamic_config/dynamic_settings.py
  ansible_base/rbac/api/related.py
  test_app/migrations/0001_initial.py
  test_app/models.py
  test_app/tests/rbac/api/test_rbac_permissions.py
Labels: Ready for review
